api_platform:
    title: '%app_project_title% API'
    version: '1.0.0'
    show_webby: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
