api_platform:
    title: '%app_project_title% API'
    version: '%app_version%'
    show_webby: false
    swagger:
        versions: [ 3 ]
        api_keys:
            JWT:
                name: 'Authorization'
                type: 'header'
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/json' ]
