sonata_admin:
    title: '%app_project_title% Admin'
    persist_filters: true
    show_mosaic_button: false
    search: false
    options:
        skin: 'skin-green'
        form_type: 'standard'
        default_icon: 'fas fa-folder'
        logo_content: 'all'
        list_action_button_content: 'icon'
        html5_validate: true
        confirm_exit: true
        use_select2: true
        use_icheck: true
        pager_links: 10
    templates:
        layout: 'admin/layout.html.twig'
    dashboard:
        blocks:
            - { type: 'sonata.admin.block.admin_list', position: 'left' }

when@dev:
    sonata_admin:
        dashboard:
            groups:
                Admin:
                    keep_open: true
