stof_doctrine_extensions:
    default_locale: '%app_default_locale%'
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: false
            translatable: false
            softdeleteable: false
            sortable: false
            tree: false
