services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
  www:
    build: docker/php
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/project
    restart: always

volumes:
  database_data:
