services:
  www:
    container_name: nectar-backend-technical-test-v1-www
    build: docker/php
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/project
    links:
      - database
    depends_on:
      - database
    networks:
      - my_network
  database:
    container_name: nectar-backend-technical-test-v1-database
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  database_data:
networks:
  my_network:
