imports:
    - { resource: 'admins.yaml' }

parameters:
    app_default_locale: '%env(string:APP_DEFAULT_LOCALE)%'
    app_version: '%env(string:APP_VERSION)%'
    app_project_title: '%env(string:APP_PROJECT_TITLE)%'
    app_admin_user_password: '%env(string:APP_ADMIN_USER_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Event Listeners
    App\Doctrine\EventListener\DoctrineFilterEventListener:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
    App\EventListener\JwtEventListener:
        tags:
            - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_authentication_success', method: 'onAuthenticationSuccessResponse' }
    # menus
    App\Menu\AdminTopRightNavMenuBuilder:
        arguments:
            - '@knp_menu.factory'
            - '@security.helper'
        tags:
            - { name: 'knp_menu.menu_builder', method: 'createTopRightUserNavMenu', alias: 'admin_user_top_right_nav_menu' }
