imports:
    - { resource: 'admins.yaml' }

parameters:
    app_default_locale: '%env(string:APP_DEFAULT_LOCALE)%'
    app_project_title: '%env(string:APP_PROJECT_TITLE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
